version: '3.8'  # Adicionando a versão do Docker Compose

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: "root"
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DATABASE}
      TOKEN_JWT: ${TOKEN_JWT}
