services:
    mysql: 
        image: mysql:8
        container_name: "mysql-2"
        environment:
            MYSQL_ROOT_PASSWORD: ${BD_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        ports:
            - "5010:3306"
        restart: always
